cfw-guide/ios.cfw.guide

_pages/en_US/package-managers.md

Open to any suggestions or changes on the description.

Add Installer 5 to Package Managers page

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-3).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-5s).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-6).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-6).md

u0 doesn't actually work on iOS 12.4.9, we do not know whether or not it was patched, but either way, when you try to use it, it'll say "unsupported" if you're on 12.4.9.

u0 shouldn't be recommended for iOS 12.4.9, it doesn't work on 12.4.9

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-3).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-4s).md
_pages/en_US/updating-to-6.1.3.md
_pages/en_US/updating-to-8.4.1.md

A jailbreak for devices on 5.0 for A5 iPad's and 5.1 for all A5(X) devices, while a thing, is tethered and something that I wouldn't recommend to new users who want to jailbreak their old devices.
This PR implements the OTA update pages for the following devices and versions:
- For the iPad 2 and iPhone 4S, iOS 6.1.3.
- For the iPad 3rd Generation, iOS 8.4.1.

Add OTA to 6.1.3 or 8.4.1 for most devices capable of doing so.

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-3).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-4).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-6s).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-7).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-se).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-6).md

Something I found recently was that, while yes, it is true that 10.0 wasn't properly usable on current devices at the time (due to Recovery Mode Loop upon updating) There were _some_ devices that possibly came with iOS 10.0 as the factory firmware.
Note that only the iPhone 7 line has been proven to have had this version, however, other devices were being sold at the same time as the iPhone 7 was announced, this would probably mean that iOS 10.0 was the factory firmware for more devices.
Note as well, that 10.0 doesn't support every jailbreak that supports 10.0.1, that being said Meridian is supported on 10.0 so nothing needs to be changed specifically for 10.0 users unless we ever plan on switching the jailbreak linked for 10.x (which I doubt we plan to do).
With that in mind, there are …

Bump possible devices with preinstalled/factory 10.0 to 10.0 rather than 10.0.1

---

_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a12.md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a13.md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a14.md
_pages/en_US/jailbreak/installing-odyssey.md
_pages/en_US/jailbreak/installing-unc0ver.md
_pages/en_US/updating-to-10.3.3.md
_pages/en_US/updating-to-14.3.md
_pages/en_US/updating-to-6.1.3.md

This PR accomplishes two different goals here:
- Solves a varying amount of typos across several pages on the guide
- Adds a notice to the u0 page, discouraging users from using u0 due to better options being present except under the specific circumstances u0 is still required for.

Fix a series of typos/issues present throughout the guide.

---

_pages/en_US/jailbreak/installing-unc0ver.md

I decided to PR this in before I went ahead with the massive PR incoming, seeing as I do feel it would make more sense to PR this thing initially, before other changes are completed.
I also decided to write the below up, mainly because of the fact that other users may see this and wonder why we are progressing with this process, **note not everything stated below is final, but this is the perceived plan moving forward**.
**Statement on unc0ver and the planned future of this page** (for people who are interested in reading the general future plans)
The long term plan is currently to maintain this page on the guide until better options come out, but to gear users who **do not require unc0ver** away from this guide and instead look at better options. The first part of this goal was completed …

Pull Request before the Massive Pull Request that's gonna be massive in size but not quantity anyways

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-8).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-3).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-4).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-5).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro-3).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro-4).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-12).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-se-2).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a11.md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a12.md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a14.md
_pages/en_US/jailbreak-types.md
_pages/en_US/jailbreak/installing-chimera.md
_pages/en_US/jailbreak/using-cydia.md
_pages/en_US/misc/credits.md
_pages/en_US/package-managers.md
_pages/en_US/updating-to-12.5.1.md

This part of the Massive Pull Request does the following:
- Changes 14.0-14.3 of tables which do not have a jailbreak on 14.x to have 'Coming Soon' text
- Adds/Alters some information on the Installing Chimera page to include information which increases success rates significantly (mainly for users who have to use life_waste)
- Swaps around the Sileo/Cydia placement in the package manager page to signify that Sileo is the preferred package manager for modern jailbreaks
- Typo/Wording fixes/changes across certain pages
- Updates my credits name to my new discord name
Changes planned for Part Two of this Mega PR include (but are not limited to):
- Troubleshooting page Rewrite
- FAQ cleanup (and possible rewrite in some areas)
- Possible new Saving Blobs guide
- Possible new Futurerestore …

Mega PR (Part One)

---

_pages/en_US/updating/restoring-to-14.3.md

Fixes the link to `ipsw.me` on the `Restoring to 14.3` page.
Now goes to `https://ipsw.me/` instead of `https://ios.cfw.guide/ipsw.me`

Fix ipsw link

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-5).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-6).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-7).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-4).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro-2).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-6s).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-7).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-se).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-7).md
_pages/en_US/jailbreak/checkra1n/installing-odysseyra1n.md
_pages/en_US/jailbreak/checkra1n/ra1n-linux.md
_pages/en_US/jailbreak/checkra1n/ra1n-macos.md
_pages/en_US/jailbreak/checkra1n/using-odysseyn1x.md
_pages/en_US/updating/updating-to-10.3.3.md
_pages/en_US/updating/updating-to-14.5.md

- Add checkra1n 0.12.3/Odysseyn1x 2.10 (aka 14.5 and M1 Mac support)
- Revert commit that added Betelguese (not permanent, just needs an update due to checkra1n no longer using zsh)
- Add M1 Notes for relevant devices
- Alter some stuff with 10.3.3

14.5 is *fun* (aka garbage)

---

_pages/en_US/saving-blobs/saving-blobs.md
_pages/en_US/saving-blobs/tss-app.md
_pages/en_US/saving-blobs/tss-web.md

I updated the blob saving guide, since the guide previously implied that you can't save blobs without a computer on A12+. I changed the blurb to be more clear about this, and added a section about getting your generator and apnonce to the saving via web section. I'm not sure how useful it really is because you still need your apnonce and generator and if you're doing that you might as well use the app but hey. I also added a note about libkernrw for Taurine users in the app section. 
Hopefully I didn't mess up the markdown or anything!

update blob saving guide

---

_pages/en_US/jailbreak/installing-odyssey.md
_pages/en_US/jailbreak/installing-taurine.md
_pages/en_US/troubleshooting.md

I added some extra errors that can appear in Taurine/Odyssey and how to solve them based on info from the Sileo discord. I also updated the err_jailbreak link to a more general name (taurine_odyssey).

Add troubleshooting info from Sileo discord

---

_pages/en_US/jailbreak/checkra1n/using-odysseyn1x.md
_pages/en_US/jailbreak/installing-taurine.md
_pages/en_US/jailbreak/installing-unc0ver.md

Following is changed:
- Odysseyn1x notice updated to be aligned with Odysseyra1n
- unc0ver version linked switched to 6.1.1 (6.1.2 is buggy garbage)
- Taurine version linked switched to 1.0.4 (1.0.5 has some issues with BSoD and somewhat rare bootloop issues)

Minor changes to some wording and versions recommended.

---

_pages/en_US/jailbreak/installing-h3lix.md

i've basically rewritten the h3lix guide to reflect the steps required on Big Sur and later. I included a link to a patcher script someone made that essentially lets you sign the ipa yourself without tripping tihmstar's DRM but i'm not sure if that's legal or whatever. 
Also this whole guide is kinda convoluted, thanks to yknow, the DRM and the fact that certain things no longer work on Big Sur and later (unless we tell people to disable SIP and Gatekeeper LOL)

Update h3lix guide to reflect changes w.r.t AltDeploy & Big Sur

---

_pages/en_US/jailbreak/checkra1n/ra1n-linux.md
_pages/en_US/jailbreak/checkra1n/using-odysseyn1x.md

checkra1n on AMD Ryzen CPU's **in most cases** will not work for users, regardless of whether or not they are using checkra1n in an actually installed thing of Linux (e.g. Ubuntu) or Odysseyn1x.
This PR adds a notice to the start of the Linux section and on the Odysseyn1x page that users using AMD Ryzen CPU's will **likely** run into issues, and that they should attempt to obtain a mac or a computer with an Intel CPU to follow the guide.

Ryzen issues with checkra1n

---

_pages/en_US/jailbreak/checkra1n/include/end-of-page.md
_pages/en_US/jailbreak/installing-taurine.md

The guides tell people to reboot their devices. This is not necessary unless people use tweaks that require injection into daemons other than SpringBoard. In that case they'd need to reboot or do a userspace reboot later anyways. For Odysseyra1n rebooting was actually the easiest way to activate libhooker in the past but with recent libhooker versions that's not needed anymore.

Remove reboot from Taurine and Odysseyra1n guides

---

docs/en_US/include/using-cydia

In Cydia, the button says "Restart SpringBoard", not "Respring". This PR fixes this.

fix wrong button text

---

docs/en_US/updating/futurerestore.md

Dimentio automatically downloads those (as they are dependencies in the control file), which means there is no need to tell the user to manually download them

Don't show instructions for downloading libkernrw/libkrw

---

docs/en_US/updating/futurerestore-help.md
docs/en_US/updating/futurerestore.md

and remove copy-pasted instructions on how to set nonce in futurerestore-help, instead, redirect the users to the original fr page to see how to set nonce

Remove instructions on adding chariz on futurerestore pages 

---

docs/.vuepress/json/bypassApps/ios.cardinal.takarekinfo.json

The bundle ID for Takarek MobilApp as returned by the iTunes lookup API is `ios.cardinal.takarekinfo`:
```
❯ curl --silent 'https://itunes.apple.com/hu/lookup?id=1464905099' | jq '.results[0].bundleId'
"ios.cardinal.takarekinfo"
```

Fix bundle ID for Takarek MobilApp

---

docs/en_US/jailbreak/checkra1n/installing-odysseyra1n/ra1n-linux.md

This PR adds specific instructions, provided by the checkra1n team, for Debian-based distros to the Linux section of the checkra1n guide. Considering that this is the method that is recommended by the checkra1n team, there's no reason to not mention this in the guide, considering how much easier it is.

checkra1n: Add instructions for Debian-based distros

---

docs/en_US/jailbreak/checkra1n/installing-odysseyra1n/index.md
docs/en_US/jailbreak/checkra1n/using-odysseyn1x-a8x-a9x.md
docs/en_US/jailbreak/checkra1n/using-odysseyn1x.md

Improve clarity for AMD64 odysseyn1x and iOS 14 A11 checkra1n SEP issue.
The "AMD64" name confuses some people, and so does the A11 checkra1n SEP issue if the user is on 13 or earlier.

Improve clarity

---

docs/en_US/updating/futurerestore.md

- Restructured the guide by a decent amount
- Now divides the guide into jailbroken and non-jailbroken, with the latter utilizing TrollNonce for non-jailbroken devices (A9-A11 devices that cannot use TrollNonce have been linked to the iOS 15 downgrade gist)
- Uses futurerestore beta for all devices as it is available on every OS now
- Made the No RSEP and Custom Latest flag mandatory
- Included a warning to check SEP/BB compatibility before continuing (spreadsheet is linked)
- Various other tweaks to bring guide more up-to-date

update futurerestore guide

---

docs/en_US/jailbreak/restoring-root-filesystem/removing-palera1n.md

The restore argument is `--restorerootfs`
https://github.com/palera1n/palera1n/blob/main/palera1n.sh#L208

Correct uninstall argument for palera1n

---

docs/en_US/jailbreak/installing-palera1n.md

I was following this guide and saw that the sentence "Put your device in DFU Mode before running this command" was put underneath the command (this is for Step 6 on Linux and Step 3 on macOS). 
I almost missed this step as it was not highlighted and because it came **after** the step itself.
I just made a small change to bold the part "before running this command" to draw more attention to it.
Thanks.

Semantic change to make guide more clear.

---

docs/en_US/updating/futurerestore.md
docs/it_IT/updating/futurerestore.md

github doesn't redirect from the old username for some reason, but removing the username ensures the link works regardless of username changes

update checkm8 downgrade gist url

---

docs/en_US/jailbreak/installing-palera1n.md

The script works better with the device turned on first, as it puts the device into recovery mode before prompting the user to enter DFU. This solves the issue of the device booting too early.

Removed instruction to enter DFU

---

docs/en_US/jailbreak/installing-palera1n.md
docs/en_US/jailbreak/restoring-root-filesystem/removing-palera1n.md

This reduces the download size from 512 MB to 107 MB, especially useful on a live USB where everything goes into the RAM.

palera1n: use shallow clone

---

docs/en_US/jailbreak/using-jailbreakme-star.md

The JailbreakMe website doesn't function properly anymore, and so the PDFs have to be selected manually.

Fixes jailbreakme Star and Saffron guides

---

docs/en_US/updating/futurerestore.md

- Removed most mentions of A12+ in the downgrading steps
- Removed notice about unc0ver on 14.6-14.8 needing to use libkrw as it is no longer relevant considering it only applies to A12-A14, which cannot follow this guide
- Added two warnings about not following the guide if you are on an iOS 16 compatible device: one at the start, and one right before setting up futurerestore-gui
- Removed Custom Latest requirement as it is not needed on devices that can follow this guide
- Add link to gist about Cryptex1 compatibility
- Added link to delayed OTA guide as an alternative way for A12+ devices to update
Overall, the guide is now much more oriented on A10- due to A12+ being unable to utilize blobs (though still links Alexia's checkm8 downgrade guide). Though A12+ _theoretically_ could …

Update futurerestore guide to reflect current upgrade/downgrade situation

---

docs/en_US/jailbreak/installing-palera1n-rootless.md
docs/en_US/jailbreak/installing-palera1n.md

General:
- Added mention of default downloads directory
macOS-specific:
- Added instructions to enable Full Disk Access for Terminal (fixes "No such file or directory" error with the `sudo mv` command)
- Added instructions to install the correct version of `xattr` on macOS Monterey 12.2.1 and below
- Updated to use `mkdir -p` to silence "File exists" error so we don't have to tell the user that it's safe to ignore

Some additions/improvements to palera1n guides

---

docs/en_US/jailbreak/installing-palera1n-rootless.md
docs/en_US/jailbreak/installing-palera1n.md

This clarifies that `palera1n-linux-x86_64` is usually the correct choice, as I've seen too many people mistakenly download the arm64 version. It also adds further clarification to help with choosing for less common setups.

Clarify which version of palera1n to get for Linux

---

docs/en_US/jailbreak/jailbreak-removal/removing-palera1n.md

A user in the jailbreak server suggested this page be fixed. `cd`ing into the palera1n directory is a confusing instruction for those who have already installed palera1n into the proper spot (and the server member even thought this was an old page for palera1n.sh). Also, these changes add a tab for removing palera1n using palen1x. 
I haven't tested how these edits look. There may be formatting mistakes (hopefully not), so if you can preview it as a page beforehand, it would be a good idea (and much appreciated)

Clarify "removing palera1n" page (and add instructions for palen1x)

---

docs/en_US/jailbreak/installing-kok3shiX.md

I know most people use socket for iOS 10 32-bit, but kok3shiX is still a good alternative

Update link to kok3shiX ipa

---

docs/en_US/jailbreak/installing-homedepot.md

The links for the Home Depot jailbreak (for iOS 8.0-8.4.1 and iOS 9.1-9.3.4) were broken and led to a scammy website, so I replaced them with working Archive.org links.

Replaced broken links with Archive.org links

---

docs/en_US/guides/sideloading-apps.md

Think the changes are pretty self-explanatory, but whatever
- Fixed ReProvision Reborn having not-capitalised "p"
- Added a dot to make formatting consistent
- Apple ID is written separately
- Added "preferred" to make similar-steps-across-guides consistent

sideloading-apps lil fixes

---

docs/en_US/jailbreak/installing-homedepot.md
docs/en_US/jailbreak/installing-kok3shi9.md

- Update Home Depot ohd step to apply the patch for all of iOS 8. This is because the "no offsets found" error also occurs on 8.4.1 even when it's supposed to be supported. Tested on iPad2,1 8.4.1.
- Corrections to UntetherHomeDepot repo name and URL.

Updates to Home Depot guide

---

docs/en_US/jailbreak/using-checkm8-a5.md

In checkm8, chipsets are defined as A5_xxxx, so A5-8940 is supposed to be A5_8940, and same for A5-8945 (A5_8945).

Fix 2 typos related to chipset names in checkm8-a5
