_pages/en_US/faq.md
_pages/en_US/home.md

Found some minor typos and fixed them. Added warnings to backup the device to iCloud or iTunes in case of data loss, added how to "recover" your warranty by restoring RootFS (unjailbreaking) or fully restoring with iTunes.

✏️ Fixed typos, added backup warnings, fixed warranty statement

---

_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-5s).md

Update iPhone 5S firmware selection

---

_pages/en_US/jailbreak/checkra1n/include/end-of-page.md
_pages/en_US/jailbreak/checkra1n/include/no-loader.md
_pages/en_US/jailbreak/checkra1n/using-odysseyn1x.md

fix capitalization
add explanation for odysseyra1n
add sileo dev mode tutorial
warn about installing cydia from loader

#TeamProcursus

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-5).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-6).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-7).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-8).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-3).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-4).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-4).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-5).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro-3).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-pro-4).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-6s).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-7).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-se).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-se-2).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-7).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a11.md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a12.md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a13.md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a14.md
_pages/en_US/jailbreak/installing-unc0ver.md
_pages/en_US/jailbreak/removing-unc0ver.md
_pages/en_US/updating-to-14.4.md

fuck my life.
should I mention unc0ver has a lot of issues on 6.0.0? no? ok then.

Add unc0ver support for 12.4.9-12.5.1, 13.5.1-13.7, and 14.0-14.3

---

_pages/en_US/jailbreak/checkra1n/installing-odysseyra1n.md
_pages/en_US/jailbreak/checkra1n/ra1n-linux.md
_pages/en_US/jailbreak/checkra1n/ra1n-macos.md
_pages/en_US/jailbreak/checkra1n/using-odysseyn1x.md
_pages/en_US/jailbreak/installing-unc0ver.md
_pages/en_US/jailbreak/removing-unc0ver.md

just read the commits I don't have the time to write a long explanation.
also VS Code hopefully solves my previous issue of fucking up tables I guess.

typo fixes, information updates, other meaningless crap, etc.

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-3).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-4).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-5s).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-6).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-6).md
_pages/en_US/jailbreak/installing-kok3shi.md

- fix ver ranges
- add iPad Mini 3 and A8(X) devices for 9.3.4-9.3.5
- fix typo in kok3shi page

update kok3shi pages

---

_pages/en_US/device-selection/device-selection-(ipad).md
_pages/en_US/device-selection/device-selection-(iphone).md
_pages/en_US/device-selection/device-selection-(ipod).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-1).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-2g).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-3g).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-3gs).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-4).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-1).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-2).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-3).md
_pages/en_US/jailbreak/using-jailbreakme-star.md
_pages/en_US/misc/site-navigation.md

Mega PR I guess...
- Add JailbreakMe Star
- Create all remaining device pages (iPhone 2G/3G, iPod Touch 1/2)
- (Attempt) to organize parts of Device Selection Pages
- Reorganize Site Navigation + Add more jailbreak methods to Site Navigation

Add JailbreakMe Star + Add All Remaining Devices

---

_pages/en_US/device-selection/device-selection-(ipod).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-7).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-7).md
_pages/en_US/jailbreak/installing-odyssey.md
_pages/en_US/jailbreak/using-jailbreakme-star.md

Mini PR:
- Switch Odyssey 1.3.0 download link to Odyssey 1.3.1b2
- Revert several commits revolving iPhone 7/iPod Touch 7 Odyssey issues
- Fix a typo on the JailbreakMe Star page
- Fix the device selection part of the iPod 1

just another PR

---

_pages/en_US/jailbreak/checkra1n/ra1n-macos.md

fix macos guide

---

_pages/en_US/device-selection/iphone-ipod/firmware-selection-iphone-a11.md
_pages/en_US/jailbreak/checkra1n/installing-odysseyra1n.md
_pages/en_US/jailbreak/checkra1n/ra1n-linux.md
_pages/en_US/jailbreak/checkra1n/ra1n-macos.md
_pages/en_US/jailbreak/checkra1n/using-odysseyn1x.md
_pages/en_US/misc/information-regarding-a11.md
_pages/en_US/updating/updating-to-14-4-(blobless).md
_pages/en_US/updating/updating-to-14.5.md

A11 and Odysseyra1n

---

_pages/en_US/misc/site-navigation.md

Miscellaneous -> Extra Pages due to the fact that it's not really "extra" imo, just doesn't categorize under Jailbreaks

Future Restore -> FutureRestore

---

_pages/en_US/saving-blobs/tss-web.md

there was a link that broke, i've fixed that link

fix link in tss-web.md

---

_pages/en_US/saving-blobs/saving-blobs.md
_pages/en_US/saving-blobs/tss-computer.md

blobsaver v3.0 was released, and added something I forgot to add earlier.

Minor fixes to "Saving Blobs" page

---

_pages/en_US/blocking-updates.md
_pages/en_US/device-selection/iphone-ipod/find-ios-version.md
_pages/en_US/faq.md
_pages/en_US/home.md
_pages/en_US/package-managers.md
_pages/en_US/troubleshooting.md
_pages/en_US/types-of-jailbreak.md

Including FAQ, Update Blocking and more

Lots of updates to the main pages of cfw-guide

---

_pages/en_US/troubleshooting.md

while trying to help someone, i realised some people may not infer that postrm is the removal script, so i made that blindingly obvious now

literally less than a line in troubleshooting bc ppl can't read

---

_pages/en_US/device-selection/ipad/firmware-selection-(ipad-2).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-3).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-4).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-air).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini).md
_pages/en_US/device-selection/ipad/firmware-selection-(ipad-mini-2).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-4s).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-5).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-5c).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-5s).md
_pages/en_US/device-selection/iphone-ipod/firmware-selection-(ipod-touch-5).md
_pages/en_US/jailbreak/checkra1n/include/end-of-page.md
_pages/en_US/jailbreak/installing-evasi0n7.md
_pages/en_US/misc/site-navigation.md

I've written up a guide for using evasi0n 7 on a windows machine. You can also use it on macOS mojave and older but as i mentioned on the discord i don't have access to that.
(also the libhooker configurator guide commits are just me being dumb and not understanding git branches so just ignore that lol)

Evasi0n guide

---

_pages/en_US/device-selection/iphone-ipod/firmware-selection-(iphone-4).md
_pages/en_US/jailbreak/installing-evasi0n7.md

as per a conversation i had with someone from r/legacyjb, i've added a note to the guide about a specific case where you need a different version of the jailbreak

add note to evasi0n guide

---

docs/en_US/jailbreak/installing-pangu7/index.md

since kawaiizenbo now hosts the pangu untether on her repo, the section about fixing the bootlooping is waaaay easier :)

simplify pangu7 guide

---

docs/.vuepress/components/versionTable.vue
docs/.vuepress/configs/sidebar/index.ts
docs/en_US/jailbreak/installing-unc0ver-fugu14/index.md
docs/en_US/jailbreak/installing-unc0ver-fugu14/using-cydia.md

This PR (hopefully) does the following
- Adds unc0ver (Fugu14)
- (On today's episode of I hate github formatting) At least the guide has more effort than pwn's effort that was put into this in the first place.
- Doesn't break shit

I hate this

---

docs/en_US/jailbreak/installing-evasi0n6.md
docs/en_US/jailbreak/installing-evasi0n7.md

i'm not entirely sure i did the linking right and i don't have a test environment for it but yeah the body of the guide for the original evasi0n is here so hopefully it's not too annoying to check the links and whatnot

added evasi0n 6 guide

---

docs/en_US/updating/futurerestore.md

- change beta warning for ios 15 devices and beta compatibility
- add warning about dimentio on later versions of u0

Modify futurerestore.md

---

docs/en_US/jailbreak/installing-absinthe.md

absinthe doesnt need older itunes apparently

---

docs/en_US/guides/saving-blobs.md
docs/en_US/jailbreak/checkra1n/installing-odysseyra1n/index.md
docs/en_US/jailbreak/checkra1n/using-odysseyn1x-a8x-a9x.md
docs/en_US/jailbreak/checkra1n/using-odysseyn1x.md

Title.
Also added my name to contributors on the pages I've edited.

Add deverser and SSH ramdisk onboard blob dumping tutorials

---

docs/en_US/guides/saving-blobs.md

Adapt to new changes, to make it easier for the user.

Edit sshrd blob dumping tutorial

---

docs/en_US/jailbreak/palera1n/include/tethered.md
docs/en_US/jailbreak/palera1n/installing-palera1n/index.md
docs/en_US/jailbreak/palera1n/installing-palera1n/palera1n-linux.md
docs/en_US/jailbreak/palera1n/installing-palera1n/palera1n-macos.md

palera1n was updated to support 15.0-15.7.1, so I updated the guide for the change of commands and stuff

Update palera1n guide

---

docs/en_US/updating/updating-blobless-advanced.md
docs/en_US/updating/updating-blobless-alternate.md

Year was 2022 instead of 2023.

Fix dates on Delayed OTA pages

---

docs/en_US/jailbreak/installing-xinaa15.md

xina sileo beta 5

---

docs/en_US/jailbreak/installing-fugu15max.md
docs/en_US/jailbreak/installing-p0sixspwn.md
docs/en_US/jailbreak/installing-taurine-trollstore.md
docs/en_US/jailbreak/installing-unc0ver-trollstore.md
docs/en_US/jailbreak/installing-zebra.md

- Use default ElleKit repo
- Use latest Fugu15 Max (instead of hardlinked Beta 4)
- No need to manually install ldid in TrollStore anymore
- Downgrade Zebra if it's in demo mode
- Do xattr on p0sixspwn
Haven't tested these edits on a live site because idk how lol

Fix some random stuff

---

docs/en_US/jailbreak/installing-palera1n.md

this accidental slash causes curl to not work and errors out with requested url not found 404, after removing this the command should work fine

remove accidental slash in the command

---

docs/en_US/updating/updating-blobless-alternate.md
docs/en_US/updating/updating-blobless.md
docs/it_IT/updating/updating-blobless-advanced.md
docs/it_IT/updating/updating-blobless.md
docs/it_IT/updating/updating-dallas.md

repo.cadoth.net -> repo.alexia.lol

Update OTAEnabler repo URL

---

docs/en_US/guides/blocking-updates.md

The other link will redirect to a UK petition if you live in the UK, which is not the tvOS profile link.

chore: change tvOS profile link

---

docs/en_US/guides/blocking-updates.md

This update tvOS 16 profile to tvOS 17 profile. It should expire less sooner than tvOS16.
All credit goes to nebula !

Updated tvOS profile

---

docs/en_US/guides/faq.md

3rd time is the charm I guess, how far can I go with this.

update the faq 3

---

docs/en_US/guides/faq.md

Ah yes, another time I update this FAQ. it's like I have an infinity supply of pull requests for this to be updated :trolley: actually who reads rhe FAQ

update the faq 4

---

docs/en_US/guides/recommended-repos.md

The last 2 repos don’t work I clarified it plus it hasn’t been updated in 2 years

Update recommended-repos.md :)

---

docs/en_US/include/using-sileo.md

Add description on how to log into repos for sileo.

Update using-sileo.md by adding info on how to log into repos

---

docs/en_US/guides/trollstore/trollrestore.md

Add a step for plugging in iOS device into the computer for macOS/Windows tab.

Additional step for macOS/Windows

---

docs/en_US/guides/trollstore/trollrestore.md

Fix typo in trollrestore.md

---

docs/en_US/guides/faq.md
docs/en_US/home.md

Fixed a grammar mistake/typo in the FAQ and added mention in the FAQ and homepage that tweaks can also allow for additional functionality; not solely visual customization.

Grammar mistake + mention of functionality
